version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    reviewers:
      - "max-messenger/developers"
      - "max-messenger/security"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "max-messenger/developers"
      - "max-messenger/security"
